#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v3
# autospec commit: 1eaf8cd
#
Name     : R-rainbow
Version  : 3.8
Release  : 13
URL      : https://cran.r-project.org/src/contrib/rainbow_3.8.tar.gz
Source0  : https://cran.r-project.org/src/contrib/rainbow_3.8.tar.gz
Summary  : Bagplots, Boxplots and Rainbow Plots for Functional Data
Group    : Development/Tools
License  : GPL-3.0
Requires: R-colorspace
Requires: R-hdrcde
Requires: R-ks
Requires: R-pcaPP
BuildRequires : R-colorspace
BuildRequires : R-hdrcde
BuildRequires : R-ks
BuildRequires : R-pcaPP
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%prep
%setup -q -n rainbow
pushd ..
cp -a rainbow buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1706024842

%install
export SOURCE_DATE_EPOCH=1706024842
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/rainbow/DESCRIPTION
/usr/lib64/R/library/rainbow/INDEX
/usr/lib64/R/library/rainbow/Meta/Rd.rds
/usr/lib64/R/library/rainbow/Meta/data.rds
/usr/lib64/R/library/rainbow/Meta/demo.rds
/usr/lib64/R/library/rainbow/Meta/features.rds
/usr/lib64/R/library/rainbow/Meta/hsearch.rds
/usr/lib64/R/library/rainbow/Meta/links.rds
/usr/lib64/R/library/rainbow/Meta/nsInfo.rds
/usr/lib64/R/library/rainbow/Meta/package.rds
/usr/lib64/R/library/rainbow/NAMESPACE
/usr/lib64/R/library/rainbow/R/rainbow
/usr/lib64/R/library/rainbow/R/rainbow.rdb
/usr/lib64/R/library/rainbow/R/rainbow.rdx
/usr/lib64/R/library/rainbow/data/Rdata.rdb
/usr/lib64/R/library/rainbow/data/Rdata.rds
/usr/lib64/R/library/rainbow/data/Rdata.rdx
/usr/lib64/R/library/rainbow/demo/SVDplot.R
/usr/lib64/R/library/rainbow/demo/fboxplot.R
/usr/lib64/R/library/rainbow/demo/fds.R
/usr/lib64/R/library/rainbow/demo/fts.R
/usr/lib64/R/library/rainbow/demo/plot.fds.R
/usr/lib64/R/library/rainbow/demo/plot.fts.R
/usr/lib64/R/library/rainbow/demo/plot.sfts.R
/usr/lib64/R/library/rainbow/demo/sfts.R
/usr/lib64/R/library/rainbow/help/AnIndex
/usr/lib64/R/library/rainbow/help/aliases.rds
/usr/lib64/R/library/rainbow/help/paths.rds
/usr/lib64/R/library/rainbow/help/rainbow.rdb
/usr/lib64/R/library/rainbow/help/rainbow.rdx
/usr/lib64/R/library/rainbow/html/00Index.html
/usr/lib64/R/library/rainbow/html/R.css
